# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
	config.vm.box = "ubuntu/xenial64"
	config.vm.box_url = "Vagrantfile"
  
	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.memory = "1024"
	end
	
    config.vm.provision :salt do |salt|
		salt.masterless = false
		salt.run_highstate = false
		config.ssh.pty = false
	end

	config.vm.define "master" do |master|
		master.vm.synced_folder "salt-commands", "/srv/salt"
		master.vm.network "private_network", ip: "192.168.50.10"

		master.vm.provision :salt do |saltmaster|
			saltmaster.install_master = true
			saltmaster.minion_config = "configs/master"
			saltmaster.minion_key = "keys/master/master.pem"
			saltmaster.minion_pub = "keys/master/master.pub"
			saltmaster.master_key = "keys/master/master.pem"
			saltmaster.master_pub = "keys/master/master.pub"
			saltmaster.seed_master = {
				master: 'keys/master/master.pub',
				minion: 'keys/minion/minion.pub'
			}
			saltmaster.install_type = "stable"
			saltmaster.verbose = true
			saltmaster.colorize = true
			saltmaster.bootstrap_options = "-F -P -c /tmp"
		end
	end

	config.vm.define "minion" do |minion|
		minion.vm.synced_folder "salt-commands", "/srv/salt"
		minion.vm.network "private_network", ip: "192.168.50.20"

		minion.vm.provision :salt do |saltminion|
			saltminion.minion_config = "configs/minion"
			saltminion.minion_key = "keys/minion/minion.pem"
			saltminion.minion_pub = "keys/minion/minion.pub"
			saltminion.install_type = "stable"
			saltminion.verbose = true
			saltminion.colorize = true
			saltminion.bootstrap_options = "-F -P -c /tmp"
		end
	end
end
