# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.box_url = "Vagrantfile"

  config.vm.network "forwarded_port", guest: 80, host: 8899

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2
     service apache2 start
  SHELL
end
